export const PRINTABLE_BOOKLET_PUZZLES_PER_PAGE = 4;

export const PRINTABLE_BOOKLET_SOLUTIONS_PER_PAGE = 4;

export const PRINTABLE_LARGE_PRINT_PUZZLES_PER_PAGE = 2;

export const PRINTABLE_LARGE_PRINT_SOLUTIONS_PER_PAGE = 4;

export const PRINTABLE_BLANK_GRID_SHEET_PAGE_COUNT = 2;

export const PRINTABLE_COVER_PAGE_COUNT = 1;
