import {
    PRINTABLE_BOOKLET_PUZZLES_PER_PAGE,
    PRINTABLE_BOOKLET_SOLUTIONS_PER_PAGE,
    PRINTABLE_LARGE_PRINT_PUZZLES_PER_PAGE,
    PRINTABLE_LARGE_PRINT_SOLUTIONS_PER_PAGE
} from './printable-layout.constant';
import { PRINTABLE_BOOKLET_SIZE, PRINTABLE_LARGE_PRINT_SIZE } from './printable-sample.constant';

const COVER_PAGE_COUNT = 1;
const BLANK_GRID_SHEET_PAGE_COUNT = 2;

export const PRINTABLE_BOOKLET_PAGE_COUNT =
    COVER_PAGE_COUNT +
    Math.ceil(PRINTABLE_BOOKLET_SIZE / PRINTABLE_BOOKLET_PUZZLES_PER_PAGE) +
    Math.ceil(PRINTABLE_BOOKLET_SIZE / PRINTABLE_BOOKLET_SOLUTIONS_PER_PAGE);

export const PRINTABLE_LARGE_PRINT_PAGE_COUNT =
    COVER_PAGE_COUNT +
    Math.ceil(PRINTABLE_LARGE_PRINT_SIZE / PRINTABLE_LARGE_PRINT_PUZZLES_PER_PAGE) +
    Math.ceil(PRINTABLE_LARGE_PRINT_SIZE / PRINTABLE_LARGE_PRINT_SOLUTIONS_PER_PAGE);

export const PRINTABLE_BLANK_GRID_PAGE_COUNT = COVER_PAGE_COUNT + BLANK_GRID_SHEET_PAGE_COUNT;
