export const PRINTABLE_BOOKLET_PUZZLES_PER_PAGE = 4;

export const PRINTABLE_BOOKLET_SOLUTIONS_PER_PAGE = 4;

export const PRINTABLE_LARGE_PRINT_PUZZLES_PER_PAGE = 2;

export const PRINTABLE_LARGE_PRINT_SOLUTIONS_PER_PAGE = 4;
