export enum ForcingOutcomeKindEnum {
    EMPTY_CELL = 'EMPTY_CELL',
    NO_POSITION = 'NO_POSITION',
    ASSIGNMENT_CONFLICT = 'ASSIGNMENT_CONFLICT',
    COMMON_PLACEMENT = 'COMMON_PLACEMENT',
    COMMON_ELIMINATIONS = 'COMMON_ELIMINATIONS'
}
