export const HELL_CORPUS_MINIMUM_GIVEN_COUNT = 17;
export const HELL_CORPUS_MAXIMUM_GIVEN_COUNT = 28;
export const HELL_CORPUS_RECORD_BYTES = 26;
export const HELL_CORPUS_RECORD_BASE64_LENGTH = 36;
export const HELL_CORPUS_MINIMUM_RATING = 7.5;
