// Generated by packages/hell-corpus/scripts/build-infinity-corpus.mjs from
// packages/hell-corpus/scripts/infinity-corpus-source.json. Do not edit by hand.
//
// The curated Infinity corpus collects publicly documented, world-record-class hard
// sudoku puzzles (Sudoku Explainer rating >= 10.0), including Arto Inkala's "Everest"
// and "AI Escargot", and the "Platinum Blonde" puzzle studied in Ercsey-Ravasz &
// Toroczkai, "The Chaos Within Sudoku" (Scientific Reports, 2012). Each entry's grid
// and rating are sourced in packages/hell-corpus/scripts/infinity-corpus-source.json.
// Ratings are the puzzle authors'/publications' claimed Sudoku Explainer ratings,
// trusted as external published values until this project's own forcing-chain rater
// can verify them in-house.
export const INFINITY_CORPUS_SIZE = 3;

export const INFINITY_CORPUS_BASE64 = 'ARhIEQEHEWFGQgA4dil1VBcThliRBAB3oSQyYSIxRCCBRABxOYJpVZOBYjRBdwNqgAEyYSgFBIMoIwAhI0OBZYeJlVR0BgBt';
