import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { GRID_CELL_COUNT, UNIQUENESS_COUNT_LIMIT } from '@suuudokuuu/solver-core';
import { BitmaskSolver } from '@suuudokuuu/solver-bitmask';
import { DLXSolver } from '@suuudokuuu/solver-dlx';

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = join(SCRIPT_DIRECTORY, '..', 'src', 'constants', 'hell-corpus-data.constant.ts');

const CLUE_COUNT = 17;
const RECORD_BYTES = 21;
const RECORD_BASE64_LENGTH = 28;
const POSITION_MASK_BYTES = 11;
const NIBBLE_MASK = 0xf;
const DEFAULT_CROSS_CHECK_STRIDE = 500;
const MAX_REPORTED_FAILURES = 20;

const BASE64_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

const GENERATED_FILE_HEADER =
    '// Generated by packages/hell-corpus/scripts/build-corpus.mjs from the tdoku 17-clue catalog. Do not edit by hand.';

const USAGE_TEXT = `Usage: yarn build:corpus --source <path> [--cross-check-stride <n>]

Download data.zip from https://raw.githubusercontent.com/t-dillon/tdoku/master/data.zip,
unzip it, and pass --source path/to/data/puzzles2_17_clue.`;

const parseArguments = argv => {
    const options = { sourcePath: null, crossCheckStride: DEFAULT_CROSS_CHECK_STRIDE };

    for (let index = 0; index < argv.length; index += 1) {
        const argument = argv[index];

        if (argument === '--source') {
            index += 1;
            options.sourcePath = argv[index];
        } else if (argument === '--cross-check-stride') {
            index += 1;
            options.crossCheckStride = Number(argv[index]);
        }
    }

    if (!options.sourcePath) {
        throw new Error(USAGE_TEXT);
    }

    return options;
};

const loadCatalogText = sourcePath => readFileSync(sourcePath, 'utf8');

const parseCatalogLines = text =>
    text
        .split('\n')
        .map(line => line.replace(/\r$/u, ''))
        .filter(line => line.length > 0 && !line.startsWith('#'))
        .map(line => line.replace(/\./gu, '0'));

const lineToGrid = line => Uint8Array.from(line, character => Number(character));

const validatePuzzleLine = (line, lineIndex, seenPuzzles, bitmaskSolver) => {
    if (!/^[0-9]{81}$/u.test(line)) {
        return `line ${lineIndex}: expected ${GRID_CELL_COUNT} digits, received "${line}"`;
    }

    const grid = lineToGrid(line);
    const givenCount = grid.reduce((count, value) => (value === 0 ? count : count + 1), 0);

    if (givenCount !== CLUE_COUNT) {
        return `line ${lineIndex}: expected ${CLUE_COUNT} givens, received ${givenCount}`;
    }

    if (seenPuzzles.has(line)) {
        return `line ${lineIndex}: duplicate puzzle`;
    }

    seenPuzzles.add(line);

    const solutionCount = bitmaskSolver.countSolutions(grid, UNIQUENESS_COUNT_LIMIT);

    if (solutionCount !== 1) {
        return `line ${lineIndex}: expected exactly one solution, BitmaskSolver found ${solutionCount}`;
    }

    return null;
};

const crossCheckPuzzleLine = (line, lineIndex, dlxSolver) => {
    const solutionCount = dlxSolver.countSolutions(lineToGrid(line), UNIQUENESS_COUNT_LIMIT);

    if (solutionCount !== 1) {
        return `line ${lineIndex}: DLX cross-check expected exactly one solution, found ${solutionCount}`;
    }

    return null;
};

const packRecord = grid => {
    const record = new Uint8Array(RECORD_BYTES);
    const givenCells = [];

    for (let cell = 0; cell < grid.length; cell += 1) {
        if (grid[cell] !== 0) {
            const byteIndex = Math.floor(cell / 8);
            const bitIndex = cell % 8;

            record[byteIndex] |= 1 << bitIndex;
            givenCells.push(cell);
        }
    }

    givenCells.forEach((cell, givenIndex) => {
        const value = grid[cell];
        const byteIndex = POSITION_MASK_BYTES + Math.floor(givenIndex / 2);

        if (givenIndex % 2 === 0) {
            record[byteIndex] |= value & NIBBLE_MASK;
        } else {
            record[byteIndex] |= (value & NIBBLE_MASK) << 4;
        }
    });

    return record;
};

const encodeBase64Bytes = bytes => {
    let result = '';

    for (let offset = 0; offset < bytes.length; offset += 3) {
        const byte0 = bytes[offset];
        const byte1 = bytes[offset + 1];
        const byte2 = bytes[offset + 2];

        result += BASE64_ALPHABET[byte0 >> 2];
        result += BASE64_ALPHABET[((byte0 & 0x3) << 4) | (byte1 >> 4)];
        result += BASE64_ALPHABET[((byte1 & 0xf) << 2) | (byte2 >> 6)];
        result += BASE64_ALPHABET[byte2 & 0x3f];
    }

    return result;
};

const packPuzzleLine = line => encodeBase64Bytes(packRecord(lineToGrid(line)));

const writeGeneratedModule = records => {
    const fileContents = [
        GENERATED_FILE_HEADER,
        `export const HELL_CORPUS_SIZE = ${records.length};`,
        '',
        `export const HELL_CORPUS_BASE64 = '${records.join('')}';`,
        ''
    ].join('\n');

    mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
    writeFileSync(OUTPUT_FILE, fileContents, 'utf8');
};

const main = () => {
    const startTime = Date.now();
    const options = parseArguments(process.argv.slice(2));
    const catalogText = loadCatalogText(options.sourcePath);
    const lines = parseCatalogLines(catalogText);

    const bitmaskSolver = new BitmaskSolver();
    const dlxSolver = new DLXSolver();
    const seenPuzzles = new Set();
    const failures = [];
    const records = [];

    lines.forEach((line, lineIndex) => {
        const failure = validatePuzzleLine(line, lineIndex, seenPuzzles, bitmaskSolver);

        if (failure) {
            failures.push(failure);

            return;
        }

        const isCrossCheckSample = lineIndex % options.crossCheckStride === 0;

        if (isCrossCheckSample) {
            const crossCheckFailure = crossCheckPuzzleLine(line, lineIndex, dlxSolver);

            if (crossCheckFailure) {
                failures.push(crossCheckFailure);

                return;
            }
        }

        records.push(packPuzzleLine(line));
    });

    if (failures.length > 0) {
        console.error(`Hell corpus build failed with ${failures.length} issue(s):`);
        failures.slice(0, MAX_REPORTED_FAILURES).forEach(failure => console.error(` - ${failure}`));
        process.exitCode = 1;

        return;
    }

    writeGeneratedModule(records);

    const elapsedMs = Date.now() - startTime;
    const totalBytes = records.length * RECORD_BYTES;
    const base64Length = records.length * RECORD_BASE64_LENGTH;

    console.log('Hell corpus build summary');
    console.log(`  puzzles verified: ${records.length}`);
    console.log(`  failures: ${failures.length}`);
    console.log(`  raw bytes: ${totalBytes}`);
    console.log(`  base64 characters: ${base64Length}`);
    console.log(`  elapsed: ${elapsedMs}ms`);
};

try {
    main();
} catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
}
