import { readFileSync } from 'node:fs';
import { availableParallelism } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { UNIQUENESS_COUNT_LIMIT, parseGridString } from '@suuudokuuu/solver-core';
import { BitmaskSolver } from '@suuudokuuu/solver-bitmask';
import { DLXSolver } from '@suuudokuuu/solver-dlx';

import { writeGeneratedCorpusModule } from './shared/generated-module-writer.mjs';
import { ratePuzzlesInParallel } from './shared/rate-puzzles-in-parallel.mjs';
import { encodeRatingByte, packPuzzleRecord } from './shared/record-packing.mjs';
import { isSinglesSolvable } from './shared/singles-solvability.mjs';
import { crossCheckPuzzleLine, validatePuzzleFormat, validateUniquePuzzle } from './shared/puzzle-verification.mjs';

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = join(SCRIPT_DIRECTORY, '..', 'src', 'constants', 'hell-corpus-data.constant.ts');

const CLUE_COUNT = 17;
const RECORD_BYTES = 22;
const RECORD_BASE64_LENGTH = 32;
const DEFAULT_CROSS_CHECK_STRIDE = 500;
const MAX_REPORTED_FAILURES = 20;
const HELL_CORPUS_MINIMUM_RATING = 6.6;
const RATING_BAND_WIDTH = 0.5;
const RATING_BAND_FLOOR = 6.5;
const CEILING_BAND_LABEL = 'ceiling';

const GENERATED_FILE_HEADER =
    '// Generated by packages/hell-corpus/scripts/build-corpus.mjs from the tdoku 17-clue catalog. Do not edit by hand.';

const USAGE_TEXT = `Usage: yarn build:corpus --source <path> [--cross-check-stride <n>] [--workers <n>]

Download data.zip from https://raw.githubusercontent.com/t-dillon/tdoku/master/data.zip,
unzip it, and pass --source path/to/data/puzzles2_17_clue.`;

const parseArguments = argv => {
    const options = { sourcePath: null, crossCheckStride: DEFAULT_CROSS_CHECK_STRIDE, workerCount: availableParallelism() };

    for (let index = 0; index < argv.length; index += 1) {
        const argument = argv[index];

        if (argument === '--source') {
            index += 1;
            options.sourcePath = argv[index];
        } else if (argument === '--cross-check-stride') {
            index += 1;
            options.crossCheckStride = Number(argv[index]);
        } else if (argument === '--workers') {
            index += 1;
            options.workerCount = Number(argv[index]);
        }
    }

    if (!options.sourcePath) {
        throw new Error(USAGE_TEXT);
    }

    if (!Number.isInteger(options.workerCount) || options.workerCount < 1) {
        throw new Error(USAGE_TEXT);
    }

    return options;
};

const loadCatalogText = sourcePath => readFileSync(sourcePath, 'utf8');

const parseCatalogLines = text =>
    text
        .split('\n')
        .map(line => line.replace(/\r$/u, ''))
        .filter(line => line.length > 0 && !line.startsWith('#'))
        .map(line => line.replace(/\./gu, '0'));

const validateHellPuzzleLine = (line, lineIndex, seenPuzzles, bitmaskSolver) => {
    const label = `line ${lineIndex}`;
    const formatFailure = validatePuzzleFormat(line, label);

    if (formatFailure) {
        return formatFailure;
    }

    const givenCount = parseGridString(line).reduce((count, value) => (value === 0 ? count : count + 1), 0);

    if (givenCount !== CLUE_COUNT) {
        return `${label}: expected ${CLUE_COUNT} givens, received ${givenCount}`;
    }

    return validateUniquePuzzle(line, label, seenPuzzles, bitmaskSolver);
};

const getRatingBandLabel = (rating, isCeiling) => {
    if (isCeiling) {
        return CEILING_BAND_LABEL;
    }

    const bandStart = RATING_BAND_FLOOR + Math.floor((rating - RATING_BAND_FLOOR) / RATING_BAND_WIDTH) * RATING_BAND_WIDTH;
    const bandEnd = bandStart + RATING_BAND_WIDTH;

    return `${bandStart.toFixed(1)}-${bandEnd.toFixed(1)}`;
};

const countByRatingBand = ratedRecords => {
    const bandCounts = new Map();

    ratedRecords.forEach(({ rating, isCeiling }) => {
        const bandLabel = getRatingBandLabel(rating, isCeiling);

        bandCounts.set(bandLabel, (bandCounts.get(bandLabel) ?? 0) + 1);
    });

    return [...bandCounts.entries()].sort(([firstLabel], [secondLabel]) => firstLabel.localeCompare(secondLabel));
};

const main = async () => {
    const startTime = Date.now();
    const options = parseArguments(process.argv.slice(2));
    const catalogText = loadCatalogText(options.sourcePath);
    const lines = parseCatalogLines(catalogText);

    const bitmaskSolver = new BitmaskSolver();
    const dlxSolver = new DLXSolver();
    const seenPuzzles = new Set();
    const failures = [];
    const candidateLines = [];
    let singlesSolvableCount = 0;

    lines.forEach((line, lineIndex) => {
        const failure = validateHellPuzzleLine(line, lineIndex, seenPuzzles, bitmaskSolver);

        if (failure) {
            failures.push(failure);

            return;
        }

        const isCrossCheckSample = lineIndex % options.crossCheckStride === 0;

        if (isCrossCheckSample) {
            const crossCheckFailure = crossCheckPuzzleLine(line, `line ${lineIndex}`, dlxSolver);

            if (crossCheckFailure) {
                failures.push(crossCheckFailure);

                return;
            }
        }

        if (isSinglesSolvable(parseGridString(line))) {
            singlesSolvableCount += 1;

            return;
        }

        candidateLines.push(line);
    });

    if (failures.length > 0) {
        console.error(`Hell corpus build failed with ${failures.length} issue(s):`);
        failures.slice(0, MAX_REPORTED_FAILURES).forEach(failure => console.error(` - ${failure}`));
        process.exitCode = 1;

        return;
    }

    const ratingStartTime = Date.now();
    const ratings = await ratePuzzlesInParallel(candidateLines, options.workerCount);
    const ratingElapsedMs = Date.now() - ratingStartTime;

    const records = [];
    const keptRatedRecords = [];
    let belowMinimumRatingCount = 0;

    candidateLines.forEach((line, candidateIndex) => {
        const { rating, isCeiling } = ratings[candidateIndex];

        if (rating < HELL_CORPUS_MINIMUM_RATING) {
            belowMinimumRatingCount += 1;

            return;
        }

        records.push(packPuzzleRecord(line, encodeRatingByte(rating, isCeiling), RECORD_BYTES));
        keptRatedRecords.push({ rating, isCeiling });
    });

    writeGeneratedCorpusModule({
        outputFile: OUTPUT_FILE,
        header: GENERATED_FILE_HEADER,
        sizeName: 'HELL_CORPUS_SIZE',
        size: records.length,
        base64Name: 'HELL_CORPUS_BASE64',
        base64: records.join('')
    });

    const elapsedMs = Date.now() - startTime;
    const totalBytes = records.length * RECORD_BYTES;
    const base64Length = records.length * RECORD_BASE64_LENGTH;

    console.log('Hell corpus build summary');
    console.log(`  puzzles verified: ${lines.length}`);
    console.log(`  singles-solvable excluded: ${singlesSolvableCount}`);
    console.log(`  rated candidates: ${candidateLines.length}`);
    console.log(`  below minimum rating (${HELL_CORPUS_MINIMUM_RATING}): ${belowMinimumRatingCount}`);
    console.log(`  puzzles kept: ${records.length}`);
    console.log(`  failures: ${failures.length}`);
    console.log(`  raw bytes: ${totalBytes}`);
    console.log(`  base64 characters: ${base64Length}`);
    console.log(`  rating workers: ${Math.max(1, Math.min(options.workerCount, candidateLines.length))}`);
    console.log(`  rating elapsed: ${ratingElapsedMs}ms`);
    console.log(`  elapsed: ${elapsedMs}ms`);
    console.log('  rating band distribution:');
    countByRatingBand(keptRatedRecords).forEach(([bandLabel, bandCount]) => console.log(`    ${bandLabel}: ${bandCount}`));
};

main().catch(error => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
});
