import { DifficultyEnum } from '@suuudokuuu/generator';

import type { TierTechniqueReportInterface } from '../interfaces/tier-technique-report.interface';

export const TIER_TECHNIQUE_REPORTS: TierTechniqueReportInterface[] = [
    {
        difficulty: DifficultyEnum.Newbie,
        clueCount: 37,
        highestClueCount: 37,
        simplerLadderMaxTechnique: null,
        bandLadderMaxTechnique: 2,
        lowestRating: 1.5,
        highestRating: 2.3,
        ceilingRatedPuzzleCount: 0,
        sampleSize: 40,
        singlesOnlyPuzzleCount: 40,
        beyondLadderPuzzleCount: 0,
        typicalHardestTechnique: 2,
        hardestTechniqueReached: 2,
        techniqueUsages: [
            { technique: 1, puzzleCount: 40 },
            { technique: 2, puzzleCount: 40 },
            { technique: 3, puzzleCount: 0 },
            { technique: 4, puzzleCount: 0 },
            { technique: 5, puzzleCount: 0 },
            { technique: 6, puzzleCount: 0 },
            { technique: 7, puzzleCount: 0 },
            { technique: 8, puzzleCount: 0 },
            { technique: 9, puzzleCount: 0 },
            { technique: 10, puzzleCount: 0 },
            { technique: 11, puzzleCount: 0 },
            { technique: 12, puzzleCount: 0 },
            { technique: 13, puzzleCount: 0 },
            { technique: 14, puzzleCount: 0 },
            { technique: 15, puzzleCount: 0 },
            { technique: 16, puzzleCount: 0 },
            { technique: 17, puzzleCount: 0 },
            { technique: 18, puzzleCount: 0 },
            { technique: 19, puzzleCount: 0 },
            { technique: 20, puzzleCount: 0 },
            { technique: 21, puzzleCount: 0 },
            { technique: 22, puzzleCount: 0 },
            { technique: 23, puzzleCount: 0 },
            { technique: 24, puzzleCount: 0 },
            { technique: 25, puzzleCount: 0 },
            { technique: 26, puzzleCount: 0 },
            { technique: 27, puzzleCount: 0 },
            { technique: 28, puzzleCount: 0 },
            { technique: 29, puzzleCount: 0 },
            { technique: 30, puzzleCount: 0 },
            { technique: 31, puzzleCount: 0 }
        ]
    },
    {
        difficulty: DifficultyEnum.Easy,
        clueCount: 31,
        highestClueCount: 31,
        simplerLadderMaxTechnique: 2,
        bandLadderMaxTechnique: 3,
        lowestRating: 1.5,
        highestRating: 2.3,
        ceilingRatedPuzzleCount: 0,
        sampleSize: 40,
        singlesOnlyPuzzleCount: 40,
        beyondLadderPuzzleCount: 0,
        typicalHardestTechnique: 3,
        hardestTechniqueReached: 3,
        techniqueUsages: [
            { technique: 1, puzzleCount: 40 },
            { technique: 2, puzzleCount: 40 },
            { technique: 3, puzzleCount: 40 },
            { technique: 4, puzzleCount: 0 },
            { technique: 5, puzzleCount: 0 },
            { technique: 6, puzzleCount: 0 },
            { technique: 7, puzzleCount: 0 },
            { technique: 8, puzzleCount: 0 },
            { technique: 9, puzzleCount: 0 },
            { technique: 10, puzzleCount: 0 },
            { technique: 11, puzzleCount: 0 },
            { technique: 12, puzzleCount: 0 },
            { technique: 13, puzzleCount: 0 },
            { technique: 14, puzzleCount: 0 },
            { technique: 15, puzzleCount: 0 },
            { technique: 16, puzzleCount: 0 },
            { technique: 17, puzzleCount: 0 },
            { technique: 18, puzzleCount: 0 },
            { technique: 19, puzzleCount: 0 },
            { technique: 20, puzzleCount: 0 },
            { technique: 21, puzzleCount: 0 },
            { technique: 22, puzzleCount: 0 },
            { technique: 23, puzzleCount: 0 },
            { technique: 24, puzzleCount: 0 },
            { technique: 25, puzzleCount: 0 },
            { technique: 26, puzzleCount: 0 },
            { technique: 27, puzzleCount: 0 },
            { technique: 28, puzzleCount: 0 },
            { technique: 29, puzzleCount: 0 },
            { technique: 30, puzzleCount: 0 },
            { technique: 31, puzzleCount: 0 }
        ]
    },
    {
        difficulty: DifficultyEnum.Medium,
        clueCount: 27,
        highestClueCount: 27,
        simplerLadderMaxTechnique: 3,
        bandLadderMaxTechnique: 12,
        lowestRating: 2.6,
        highestRating: 3.4,
        ceilingRatedPuzzleCount: 0,
        sampleSize: 40,
        singlesOnlyPuzzleCount: 0,
        beyondLadderPuzzleCount: 0,
        typicalHardestTechnique: 4,
        hardestTechniqueReached: 10,
        techniqueUsages: [
            { technique: 1, puzzleCount: 40 },
            { technique: 2, puzzleCount: 40 },
            { technique: 3, puzzleCount: 40 },
            { technique: 4, puzzleCount: 37 },
            { technique: 5, puzzleCount: 5 },
            { technique: 6, puzzleCount: 14 },
            { technique: 7, puzzleCount: 13 },
            { technique: 8, puzzleCount: 5 },
            { technique: 9, puzzleCount: 1 },
            { technique: 10, puzzleCount: 1 },
            { technique: 11, puzzleCount: 0 },
            { technique: 12, puzzleCount: 0 },
            { technique: 13, puzzleCount: 0 },
            { technique: 14, puzzleCount: 0 },
            { technique: 15, puzzleCount: 0 },
            { technique: 16, puzzleCount: 0 },
            { technique: 17, puzzleCount: 0 },
            { technique: 18, puzzleCount: 0 },
            { technique: 19, puzzleCount: 0 },
            { technique: 20, puzzleCount: 0 },
            { technique: 21, puzzleCount: 0 },
            { technique: 22, puzzleCount: 0 },
            { technique: 23, puzzleCount: 0 },
            { technique: 24, puzzleCount: 0 },
            { technique: 25, puzzleCount: 0 },
            { technique: 26, puzzleCount: 0 },
            { technique: 27, puzzleCount: 0 },
            { technique: 28, puzzleCount: 0 },
            { technique: 29, puzzleCount: 0 },
            { technique: 30, puzzleCount: 0 },
            { technique: 31, puzzleCount: 0 }
        ]
    },
    {
        difficulty: DifficultyEnum.Hard,
        clueCount: 26,
        highestClueCount: 26,
        simplerLadderMaxTechnique: 12,
        bandLadderMaxTechnique: 22,
        lowestRating: 3.2,
        highestRating: 4.4,
        ceilingRatedPuzzleCount: 0,
        sampleSize: 40,
        singlesOnlyPuzzleCount: 0,
        beyondLadderPuzzleCount: 0,
        typicalHardestTechnique: 22,
        hardestTechniqueReached: 22,
        techniqueUsages: [
            { technique: 1, puzzleCount: 40 },
            { technique: 2, puzzleCount: 40 },
            { technique: 3, puzzleCount: 40 },
            { technique: 4, puzzleCount: 30 },
            { technique: 5, puzzleCount: 5 },
            { technique: 6, puzzleCount: 15 },
            { technique: 7, puzzleCount: 20 },
            { technique: 8, puzzleCount: 10 },
            { technique: 9, puzzleCount: 5 },
            { technique: 10, puzzleCount: 0 },
            { technique: 11, puzzleCount: 1 },
            { technique: 12, puzzleCount: 0 },
            { technique: 13, puzzleCount: 7 },
            { technique: 14, puzzleCount: 1 },
            { technique: 15, puzzleCount: 0 },
            { technique: 16, puzzleCount: 16 },
            { technique: 17, puzzleCount: 7 },
            { technique: 18, puzzleCount: 13 },
            { technique: 19, puzzleCount: 0 },
            { technique: 20, puzzleCount: 16 },
            { technique: 21, puzzleCount: 1 },
            { technique: 22, puzzleCount: 11 },
            { technique: 23, puzzleCount: 0 },
            { technique: 24, puzzleCount: 0 },
            { technique: 25, puzzleCount: 0 },
            { technique: 26, puzzleCount: 0 },
            { technique: 27, puzzleCount: 0 },
            { technique: 28, puzzleCount: 0 },
            { technique: 29, puzzleCount: 0 },
            { technique: 30, puzzleCount: 0 },
            { technique: 31, puzzleCount: 0 }
        ]
    },
    {
        difficulty: DifficultyEnum.Nightmare,
        clueCount: 25,
        highestClueCount: 25,
        simplerLadderMaxTechnique: 22,
        bandLadderMaxTechnique: 26,
        lowestRating: 4.5,
        highestRating: 7.2,
        ceilingRatedPuzzleCount: 0,
        sampleSize: 40,
        singlesOnlyPuzzleCount: 0,
        beyondLadderPuzzleCount: 0,
        typicalHardestTechnique: 26,
        hardestTechniqueReached: 26,
        techniqueUsages: [
            { technique: 1, puzzleCount: 40 },
            { technique: 2, puzzleCount: 40 },
            { technique: 3, puzzleCount: 40 },
            { technique: 4, puzzleCount: 38 },
            { technique: 5, puzzleCount: 11 },
            { technique: 6, puzzleCount: 24 },
            { technique: 7, puzzleCount: 21 },
            { technique: 8, puzzleCount: 12 },
            { technique: 9, puzzleCount: 6 },
            { technique: 10, puzzleCount: 0 },
            { technique: 11, puzzleCount: 1 },
            { technique: 12, puzzleCount: 0 },
            { technique: 13, puzzleCount: 7 },
            { technique: 14, puzzleCount: 0 },
            { technique: 15, puzzleCount: 0 },
            { technique: 16, puzzleCount: 21 },
            { technique: 17, puzzleCount: 12 },
            { technique: 18, puzzleCount: 3 },
            { technique: 19, puzzleCount: 3 },
            { technique: 20, puzzleCount: 10 },
            { technique: 21, puzzleCount: 10 },
            { technique: 22, puzzleCount: 18 },
            { technique: 23, puzzleCount: 4 },
            { technique: 24, puzzleCount: 27 },
            { technique: 25, puzzleCount: 0 },
            { technique: 26, puzzleCount: 21 },
            { technique: 27, puzzleCount: 0 },
            { technique: 28, puzzleCount: 0 },
            { technique: 29, puzzleCount: 0 },
            { technique: 30, puzzleCount: 0 },
            { technique: 31, puzzleCount: 0 }
        ]
    },
    {
        difficulty: DifficultyEnum.Hell,
        clueCount: 17,
        highestClueCount: 28,
        simplerLadderMaxTechnique: 26,
        bandLadderMaxTechnique: null,
        lowestRating: 7.5,
        highestRating: 8.1,
        ceilingRatedPuzzleCount: 0,
        sampleSize: 40,
        singlesOnlyPuzzleCount: 0,
        beyondLadderPuzzleCount: 0,
        typicalHardestTechnique: 29,
        hardestTechniqueReached: 29,
        techniqueUsages: [
            { technique: 1, puzzleCount: 40 },
            { technique: 2, puzzleCount: 40 },
            { technique: 3, puzzleCount: 40 },
            { technique: 4, puzzleCount: 40 },
            { technique: 5, puzzleCount: 21 },
            { technique: 6, puzzleCount: 31 },
            { technique: 7, puzzleCount: 27 },
            { technique: 8, puzzleCount: 27 },
            { technique: 9, puzzleCount: 11 },
            { technique: 10, puzzleCount: 6 },
            { technique: 11, puzzleCount: 1 },
            { technique: 12, puzzleCount: 0 },
            { technique: 13, puzzleCount: 4 },
            { technique: 14, puzzleCount: 4 },
            { technique: 15, puzzleCount: 0 },
            { technique: 16, puzzleCount: 27 },
            { technique: 17, puzzleCount: 14 },
            { technique: 18, puzzleCount: 7 },
            { technique: 19, puzzleCount: 6 },
            { technique: 20, puzzleCount: 10 },
            { technique: 21, puzzleCount: 10 },
            { technique: 22, puzzleCount: 13 },
            { technique: 23, puzzleCount: 4 },
            { technique: 24, puzzleCount: 16 },
            { technique: 25, puzzleCount: 0 },
            { technique: 26, puzzleCount: 36 },
            { technique: 27, puzzleCount: 2 },
            { technique: 28, puzzleCount: 0 },
            { technique: 29, puzzleCount: 40 },
            { technique: 30, puzzleCount: 0 },
            { technique: 31, puzzleCount: 0 }
        ]
    }
];
