export const CLARITY_PROJECT_ID_ENVIRONMENT_VARIABLE = 'NEXT_PUBLIC_CLARITY_PROJECT_ID';

export const VERCEL_ENVIRONMENT_VARIABLE = 'VERCEL';

export const VERCEL_ENVIRONMENT_NAME_VARIABLE = 'VERCEL_ENV';

export const VERCEL_DEPLOYMENT_FLAG = '1';

export const VERCEL_PRODUCTION_ENVIRONMENT_NAME = 'production';
