import { SolutionTechniqueEnum } from '@suuudokuuu/techniques';

import { BreadcrumbListItem } from '../../seo/components/breadcrumb-list-item/breadcrumb-list-item';
import { Faq } from '../../seo/components/faq/faq';
import { FaqAnswer } from '../../seo/components/faq-answer/faq-answer';
import { FaqHeading } from '../../seo/components/faq-heading/faq-heading';
import { FaqPage } from '../../seo/components/faq-page/faq-page';
import { FaqQuestion } from '../../seo/components/faq-question/faq-question';
import { ItemListSchema } from '../../seo/components/item-list-schema/item-list-schema';
import { PageHeader } from '../../seo/components/page-header/page-header';
import { buildPageMetadata } from '../../seo/utils/build-page-metadata.util';
import { TechniqueLink } from '../../techniques/components/technique-link/technique-link';
import { TechniqueSummary } from '../../techniques/components/technique-summary/technique-summary';
import { TECHNIQUE_NAMES } from '../../techniques/constants/technique-name.constant';
import { TECHNIQUE_PAGE_LADDER } from '../../techniques/constants/technique-page-ladder.constant';
import { TECHNIQUE_PAGE_PATHS } from '../../techniques/constants/technique-page-path.constant';
import { homePageMetadata } from '../metadata';

import { techniquesPageMetadata } from './metadata';

import type { Metadata } from 'next';

export const metadata: Metadata = buildPageMetadata(techniquesPageMetadata);

const TECHNIQUE_INDEX_ITEMS = TECHNIQUE_PAGE_LADDER.map(technique => ({
    path: TECHNIQUE_PAGE_PATHS[technique],
    title: TECHNIQUE_NAMES[technique]
}));

// eslint-disable-next-line max-lines-per-function -- Long-form article copy belongs in the route file
const TechniquesPage = () => (
    <main>
        <PageHeader metadata={techniquesPageMetadata}>
            <BreadcrumbListItem path={homePageMetadata.path}>Home</BreadcrumbListItem>
            <BreadcrumbListItem>Sudoku techniques</BreadcrumbListItem>
        </PageHeader>
        <ItemListSchema items={TECHNIQUE_INDEX_ITEMS} metadata={techniquesPageMetadata} />
        <p>
            A Sudoku technique is a named pattern of candidates that justifies placing a digit or erasing a candidate without guessing. This
            page lists the techniques in the order a solver should try them, from the single cheapest deduction in the game to the subset
            patterns that unlock most mid-difficulty puzzles.
        </p>
        <p>
            Every technique page here carries a worked example board that was produced by running the solving engine bundled with the
            Suuudokuuu app over a real puzzle position. The highlighted pattern cells, the eliminated candidates and the placement under
            each board are the engine’s own output, so the explanation and the diagram can never drift apart.
        </p>
        <TechniqueSummary>
            <ul>
                <li>A Sudoku technique is a named candidate pattern that justifies one placement or one elimination without guessing.</li>
                <li>Try them in cost order: singles, then intersections, then subsets, then fish, then wings, then chains.</li>
                <li>Singles alone finish an easy puzzle; subsets and intersections carry most mid-difficulty puzzles.</li>
                <li>Every technique page below carries a worked example generated by the solving engine bundled with the app.</li>
            </ul>
        </TechniqueSummary>
        <h2>Tier 1 — Singles</h2>
        <p>
            Singles place a digit directly. They need no elimination pattern, they never remove a candidate without also solving a cell, and
            a puzzle solvable with singles alone is what most apps call easy.
        </p>
        <ul className="technique-index">
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.FullHouse} /> — the last empty cell in a row, column or box takes the one
                digit that unit is still missing.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.NakedSingle} /> — a cell whose row, column and box between them rule out
                eight digits, leaving one candidate.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.HiddenSingle} /> — a digit that fits in only one cell of a unit, even though
                that cell still has other candidates.
            </li>
        </ul>
        <h2>Tier 2 — Intersections</h2>
        <p>
            Intersection techniques work on the overlap between a box and a line. They never place a digit on their own; they remove
            candidates, and those removals usually expose a single on the next pass.
        </p>
        <ul className="technique-index">
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.PointingPair} /> — a digit confined to two cells of a box that share a line
                is erased from the rest of that line.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.PointingTriple} /> — the same deduction with three cells instead of two.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.BoxLineReduction} /> — the mirror image: a digit confined to one box along a
                line is erased from the rest of that box.
            </li>
        </ul>
        <h2>Tier 3 — Subsets</h2>
        <p>
            Subsets reserve a group of digits for a group of cells. Naked subsets are found by looking at cells and counting the digits they
            can hold; hidden subsets are found by looking at digits and counting the cells that can hold them. Both are elimination
            techniques, and both scale from two cells up to four.
        </p>
        <ul className="technique-index">
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.NakedPair} /> — two cells in a unit hold the same two candidates and nothing
                else.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.NakedTriple} /> — three cells whose candidates together use only three
                digits.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.NakedQuad} /> — four cells whose candidates together use only four digits.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.HiddenPair} /> — two digits that fit in only two cells of a unit.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.HiddenTriple} /> — three digits confined to the same three cells.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.HiddenQuad} /> — four digits confined to the same four cells.
            </li>
        </ul>
        <h2>Tier 4 — Fish, wings and chains</h2>
        <p>
            Beyond the subsets, techniques stop reasoning about a single unit and start reasoning across two or more units, or across a path
            of cells, at once. Fish patterns trap a digit in the same set of rows and columns; wings link a small handful of cells through
            shared candidates; chains follow strong and weak links as far as the board allows. These are the techniques that carry the
            hardest puzzles Suuudokuuu generates.
        </p>
        <ul className="technique-index">
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.XWing} /> — a digit confined to the same two columns across two rows is
                erased from the rest of those columns.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.Swordfish} /> — the same fish pattern spread across three lines instead of
                two.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.Jellyfish} /> — the same fish pattern spread across four lines.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.FinnedXWing} /> — an X-Wing with one extra candidate that still supports a
                smaller, safe set of eliminations.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.FinnedSwordfish} /> — the same fin logic applied to a Swordfish.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.SashimiXWing} /> — a finned X-Wing where one base line is missing its normal
                corner candidate entirely.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.SashimiSwordfish} /> — the same missing-corner pattern applied to a
                Swordfish.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.XYWing} /> — three bivalue cells arranged so a shared candidate can be
                erased from any cell that sees both pincers.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.XYZWing} /> — an XY-Wing whose pivot also carries the shared candidate,
                tightening the elimination further.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.WWing} /> — two matching bivalue cells tied together by a strong link on one
                of their shared candidates.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.XChain} /> — a chain of strong and weak links on one digit connecting two
                cells that share a peer.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.XYChain} /> — a chain of bivalue cells whose two endpoints force an
                elimination wherever they overlap.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.SimpleColoring} /> — a two-color network of strong links on one digit,
                cleared wherever a cell sees both colors.
            </li>
            <li>
                <TechniqueLink technique={SolutionTechniqueEnum.AIC} /> — an alternating inference chain that generalises the fish, wing and
                chain patterns above into one technique.
            </li>
        </ul>
        <h2>How to use this list</h2>
        <p>
            Work down the list, not across it. A solver that reaches for a naked quad while an unspotted hidden single is sitting on the
            board is doing far more work than the puzzle asks for, and the same is true of a human. Suuudokuuu applies the techniques in
            exactly the order above and stops at the first one that fires, which is also how the app decides what to show when you ask for a
            hint.
        </p>
        <p>
            The fish patterns, the wings and the chains above follow the same principle as the subsets — reserving digits for cells — but
            they reason across two or more units at once, or across a path of cells, rather than inside a single unit.
        </p>
        <FaqPage>
            <FaqHeading>Sudoku techniques FAQ</FaqHeading>
            <Faq>
                <FaqQuestion>What order should I learn sudoku techniques in?</FaqQuestion>
                <FaqAnswer>
                    The order on this page: singles first, then intersections, then subsets, then fish, wings and chains. Each tier only
                    becomes necessary once every cheaper technique has been tried and failed.
                </FaqAnswer>
            </Faq>
            <Faq>
                <FaqQuestion>Do sudoku techniques ever guess a digit?</FaqQuestion>
                <FaqAnswer>
                    No. Every technique on this list justifies one placement or one elimination from the rules alone, without assuming a
                    value and checking whether it leads to a contradiction.
                </FaqAnswer>
            </Faq>
            <Faq>
                <FaqQuestion>Which technique should I try first on a stuck puzzle?</FaqQuestion>
                <FaqAnswer>
                    Whichever sits highest on this list that you have not already checked. Suuudokuuu’s hint feature does the same thing: it
                    applies the techniques in the order above and stops at the first one that fires.
                </FaqAnswer>
            </Faq>
            <Faq>
                <FaqQuestion>Why does every technique page show a worked example instead of a diagram?</FaqQuestion>
                <FaqAnswer>
                    Because a hand-drawn diagram can drift from the prose that describes it. Every worked example on this site is produced
                    by running the same solving engine bundled with the app over a real puzzle position.
                </FaqAnswer>
            </Faq>
        </FaqPage>
    </main>
);

export default TechniquesPage;
