import Link from 'next/link';

import { BreadcrumbListItem } from '../../seo/components/breadcrumb-list-item/breadcrumb-list-item';
import { Breadcrumbs } from '../../seo/components/breadcrumbs/breadcrumbs';
import { buildPageMetadata } from '../../seo/utils/build-page-metadata.util';
import { TechniqueSummary } from '../../techniques/components/technique-summary/technique-summary';
import { homePageMetadata } from '../metadata';

import { aicPageMetadata } from './aic/metadata';
import { boxLineReductionPageMetadata } from './box-line-reduction/metadata';
import { finnedSwordfishPageMetadata } from './finned-swordfish/metadata';
import { finnedXWingPageMetadata } from './finned-x-wing/metadata';
import { fullHousePageMetadata } from './full-house/metadata';
import { hiddenPairPageMetadata } from './hidden-pair/metadata';
import { hiddenQuadPageMetadata } from './hidden-quad/metadata';
import { hiddenSinglePageMetadata } from './hidden-single/metadata';
import { hiddenTriplePageMetadata } from './hidden-triple/metadata';
import { jellyfishPageMetadata } from './jellyfish/metadata';
import { techniquesPageMetadata } from './metadata';
import { nakedPairPageMetadata } from './naked-pair/metadata';
import { nakedQuadPageMetadata } from './naked-quad/metadata';
import { nakedSinglePageMetadata } from './naked-single/metadata';
import { nakedTriplePageMetadata } from './naked-triple/metadata';
import { pointingPairPageMetadata } from './pointing-pair/metadata';
import { pointingTriplePageMetadata } from './pointing-triple/metadata';
import { sashimiSwordfishPageMetadata } from './sashimi-swordfish/metadata';
import { sashimiXWingPageMetadata } from './sashimi-x-wing/metadata';
import { simpleColoringPageMetadata } from './simple-coloring/metadata';
import { swordfishPageMetadata } from './swordfish/metadata';
import { wWingPageMetadata } from './w-wing/metadata';
import { xChainPageMetadata } from './x-chain/metadata';
import { xWingPageMetadata } from './x-wing/metadata';
import { xyChainPageMetadata } from './xy-chain/metadata';
import { xyWingPageMetadata } from './xy-wing/metadata';
import { xyzWingPageMetadata } from './xyz-wing/metadata';

import type { Metadata } from 'next';

export const metadata: Metadata = buildPageMetadata(techniquesPageMetadata);

// eslint-disable-next-line max-lines-per-function -- Long-form article copy belongs in the route file
const TechniquesPage = () => (
    <main>
        <Breadcrumbs>
            <BreadcrumbListItem path={homePageMetadata.path}>Home</BreadcrumbListItem>
            <BreadcrumbListItem>Sudoku techniques</BreadcrumbListItem>
        </Breadcrumbs>
        <h1>Sudoku Techniques</h1>
        <p>
            A Sudoku technique is a named pattern of candidates that justifies placing a digit or erasing a candidate without guessing. This
            page lists the techniques in the order a solver should try them, from the single cheapest deduction in the game to the subset
            patterns that unlock most mid-difficulty puzzles.
        </p>
        <p>
            Every technique page here carries a worked example board that was produced by running the solving engine bundled with the
            Suuudokuuu app over a real puzzle position. The highlighted pattern cells, the eliminated candidates and the placement under
            each board are the engine’s own output, so the explanation and the diagram can never drift apart.
        </p>
        <TechniqueSummary>
            <ul>
                <li>A Sudoku technique is a named candidate pattern that justifies one placement or one elimination without guessing.</li>
                <li>Try them in cost order: singles, then intersections, then subsets, then fish, then wings, then chains.</li>
                <li>Singles alone finish an easy puzzle; subsets and intersections carry most mid-difficulty puzzles.</li>
                <li>Every technique page below carries a worked example generated by the solving engine bundled with the app.</li>
            </ul>
        </TechniqueSummary>
        <h2>Tier 1 — Singles</h2>
        <p>
            Singles place a digit directly. They need no elimination pattern, they never remove a candidate without also solving a cell, and
            a puzzle solvable with singles alone is what most apps call easy.
        </p>
        <ul className="technique-index">
            <li>
                <Link href={fullHousePageMetadata.path}>Full House</Link> — the last empty cell in a row, column or box takes the one digit
                that unit is still missing.
            </li>
            <li>
                <Link href={nakedSinglePageMetadata.path}>Naked Single</Link> — a cell whose row, column and box between them rule out eight
                digits, leaving one candidate.
            </li>
            <li>
                <Link href={hiddenSinglePageMetadata.path}>Hidden Single</Link> — a digit that fits in only one cell of a unit, even though
                that cell still has other candidates.
            </li>
        </ul>
        <h2>Tier 2 — Intersections</h2>
        <p>
            Intersection techniques work on the overlap between a box and a line. They never place a digit on their own; they remove
            candidates, and those removals usually expose a single on the next pass.
        </p>
        <ul className="technique-index">
            <li>
                <Link href={pointingPairPageMetadata.path}>Pointing Pair</Link> — a digit confined to two cells of a box that share a line
                is erased from the rest of that line.
            </li>
            <li>
                <Link href={pointingTriplePageMetadata.path}>Pointing Triple</Link> — the same deduction with three cells instead of two.
            </li>
            <li>
                <Link href={boxLineReductionPageMetadata.path}>Box Line Reduction</Link> — the mirror image: a digit confined to one box
                along a line is erased from the rest of that box.
            </li>
        </ul>
        <h2>Tier 3 — Subsets</h2>
        <p>
            Subsets reserve a group of digits for a group of cells. Naked subsets are found by looking at cells and counting the digits they
            can hold; hidden subsets are found by looking at digits and counting the cells that can hold them. Both are elimination
            techniques, and both scale from two cells up to four.
        </p>
        <ul className="technique-index">
            <li>
                <Link href={nakedPairPageMetadata.path}>Naked Pair</Link> — two cells in a unit hold the same two candidates and nothing
                else.
            </li>
            <li>
                <Link href={nakedTriplePageMetadata.path}>Naked Triple</Link> — three cells whose candidates together use only three digits.
            </li>
            <li>
                <Link href={nakedQuadPageMetadata.path}>Naked Quad</Link> — four cells whose candidates together use only four digits.
            </li>
            <li>
                <Link href={hiddenPairPageMetadata.path}>Hidden Pair</Link> — two digits that fit in only two cells of a unit.
            </li>
            <li>
                <Link href={hiddenTriplePageMetadata.path}>Hidden Triple</Link> — three digits confined to the same three cells.
            </li>
            <li>
                <Link href={hiddenQuadPageMetadata.path}>Hidden Quad</Link> — four digits confined to the same four cells.
            </li>
        </ul>
        <h2>Tier 4 — Fish, wings and chains</h2>
        <p>
            Beyond the subsets, techniques stop reasoning about a single unit and start reasoning across two or more units, or across a path
            of cells, at once. Fish patterns trap a digit in the same set of rows and columns; wings link a small handful of cells through
            shared candidates; chains follow strong and weak links as far as the board allows. These are the techniques that carry the
            hardest puzzles Suuudokuuu generates.
        </p>
        <ul className="technique-index">
            <li>
                <Link href={xWingPageMetadata.path}>X-Wing</Link> — a digit confined to the same two columns across two rows is erased from
                the rest of those columns.
            </li>
            <li>
                <Link href={swordfishPageMetadata.path}>Swordfish</Link> — the same fish pattern spread across three lines instead of two.
            </li>
            <li>
                <Link href={jellyfishPageMetadata.path}>Jellyfish</Link> — the same fish pattern spread across four lines.
            </li>
            <li>
                <Link href={finnedXWingPageMetadata.path}>Finned X-Wing</Link> — an X-Wing with one extra candidate that still supports a
                smaller, safe set of eliminations.
            </li>
            <li>
                <Link href={finnedSwordfishPageMetadata.path}>Finned Swordfish</Link> — the same fin logic applied to a Swordfish.
            </li>
            <li>
                <Link href={sashimiXWingPageMetadata.path}>Sashimi X-Wing</Link> — a finned X-Wing where one base line is missing its normal
                corner candidate entirely.
            </li>
            <li>
                <Link href={sashimiSwordfishPageMetadata.path}>Sashimi Swordfish</Link> — the same missing-corner pattern applied to a
                Swordfish.
            </li>
            <li>
                <Link href={xyWingPageMetadata.path}>XY-Wing</Link> — three bivalue cells arranged so a shared candidate can be erased from
                any cell that sees both pincers.
            </li>
            <li>
                <Link href={xyzWingPageMetadata.path}>XYZ-Wing</Link> — an XY-Wing whose pivot also carries the shared candidate, tightening
                the elimination further.
            </li>
            <li>
                <Link href={wWingPageMetadata.path}>W-Wing</Link> — two matching bivalue cells tied together by a strong link on one of
                their shared candidates.
            </li>
            <li>
                <Link href={xChainPageMetadata.path}>X-Chain</Link> — a chain of strong and weak links on one digit connecting two cells
                that share a peer.
            </li>
            <li>
                <Link href={xyChainPageMetadata.path}>XY-Chain</Link> — a chain of bivalue cells whose two endpoints force an elimination
                wherever they overlap.
            </li>
            <li>
                <Link href={simpleColoringPageMetadata.path}>Simple Coloring</Link> — a two-color network of strong links on one digit,
                cleared wherever a cell sees both colors.
            </li>
            <li>
                <Link href={aicPageMetadata.path}>AIC</Link> — an alternating inference chain that generalises the fish, wing and chain
                patterns above into one technique.
            </li>
        </ul>
        <h2>How to use this list</h2>
        <p>
            Work down the list, not across it. A solver that reaches for a naked quad while an unspotted hidden single is sitting on the
            board is doing far more work than the puzzle asks for, and the same is true of a human. Suuudokuuu applies the techniques in
            exactly the order above and stops at the first one that fires, which is also how the app decides what to show when you ask for a
            hint.
        </p>
        <p>
            The fish patterns, the wings and the chains above follow the same principle as the subsets — reserving digits for cells — but
            they reason across two or more units at once, or across a path of cells, rather than inside a single unit.
        </p>
    </main>
);

export default TechniquesPage;
